core/urls.py
from django.contrib import admin
from django.urls import path, include

# --Static file Configurations-----------------
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView
from django.contrib.auth.views import LogoutView
from superuser.views import certificate_for_participant, preview_certificate, quiz_attempt_form
from accounts.views import *

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('login'), permanent=True)),
    path('events/<int:event_id>/certificate_for_participant/', certificate_for_participant,
         name='certificate_for_participant'),
    path('preview_certificate/<int:id>/', preview_certificate, name='preview_certificate'),
    path('quiz/<int:quiz_id>/quiz_attempt/', quiz_attempt_form, name='quiz_attempt_form'),

    path('error_page/', error_page, name="error_page"),
    path('accounts/', include('accounts.urls')),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('dashboard/', include('superuser.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

superuser/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
statusChoices = [('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')]


class EventCategory(models.Model):
    title = models.CharField(max_length=2000, unique=True)
    description = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title


class Event(models.Model):
    category = models.ForeignKey(EventCategory, on_delete=models.CASCADE)
    logo = models.ImageField(upload_to='media')
    background_img = models.ImageField(upload_to='media', null=True, blank=True)
    title = models.CharField(max_length=2000, unique=True)
    description = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=200, choices=statusChoices, default='Pending')
    event_date = models.DateTimeField(default=datetime.now, null=True, blank=True)
    cpd_approval_no = models.CharField(max_length=512, null=True, blank=True)
    cpd_org_no = models.CharField(max_length=512, null=True, blank=True)
    location = models.CharField(max_length=512, null=True, blank=True)
    points = models.FloatField(null=True, blank=True)
    mumaris_days = models.IntegerField(null=True, blank=True)
    accreditation_no = models.CharField(max_length=512, null=True, blank=True)
    facility_number = models.CharField(max_length=512, null=True, blank=True)
    is_quiz_required = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title + " of " + self.category.title


class EventParticipant(models.Model):
    event_category = models.ForeignKey(EventCategory, on_delete=models.CASCADE, null=True, blank=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True, blank=True)
    firstName = models.CharField(max_length=2000)
    lastName = models.CharField(max_length=2000)
    email = models.EmailField()
    SCFHS_No = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=50, null=True, blank=True)
    country = models.CharField(max_length=250, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.firstName + " " + self.lastName


class EventCertificate(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, default=None, null=True, blank=True)
    eventParticipant = models.ForeignKey(EventParticipant, on_delete=models.CASCADE)
    certificate_number = models.CharField(max_length=2000)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        if self.event is not None:
            return f"{self.certificate_number} - {self.event.title}"
        else:
            return f"{self.certificate_number} - <no event>"


class Quiz(models.Model):
    eventCategory = models.ForeignKey(EventCategory, on_delete=models.CASCADE, default=None, null=True, blank=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, default=None, null=True, blank=True)
    title = models.CharField(max_length=2000, unique=True)
    description = models.CharField(max_length=2000, unique=True)
    end_Date_Time = models.DateTimeField(default=datetime.now)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=2000)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class SubmittedAnswer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    is_submitted_answer_correct = models.BooleanField(default=False)
    submitted_by = models.ForeignKey(User, on_delete=models.CASCADE)

templates/questions/create.html
{% extends "core/admin_base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block page_title %}
<title>Quiz Questions</title>
{% endblock page_title %}

{% block head %}
{% endblock head %}

{% block content %}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">{% if form.instance.id %}Edit {% else %}Create {% endif %}Question For "{{quiz.title}}"</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">Quiz Questions</li>
                        <li class="breadcrumb-item"><a href="{% url 'quiz_questions' quiz.id %}">Quiz Questions List</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">{% if form.instance.id %}Edit {% else %}Create {% endif %}</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
                <form method="POST">
                <div class="card-body">
                  {% csrf_token %}
                    <h3>Question</h3>
                    <div class="input-group control-group mb-2">
                        <input type="text" name="question" class="form-control" placeholder="Question Text" required>
                    </div>

                    <h3>Answers for a question</h3>
                    <div class="input-group">

                        <input type="radio" name="answer" required>
                        <input type="text" name="answer" class="form-control ml-3" placeholder="Answer Text" required>
                    </div>
                    <div class="input-group control-group after-add-more mt-3">

                        <input type="radio" name="answer">
                        <input type="text" name="answer" class="form-control ml-3" placeholder="Answer Text" required>
                        <div class="input-group-btn">
                            <button class="btn btn-success add-more" type="button"><i
                                    class="bi bi-plus-lg"></i>
                            </button>
                        </div>
                    </div>
                    <div class="copy-fields" style="display: none">
                        <div class="control-group input-group" style="margin-top:10px">
                            <input type="radio" name="answer" class="pr-2">
                            <input type="text" name="answer" class="form-control ml-3" placeholder="Answer Text">
                            <div class="input-group-btn">
                                <button class="btn btn-danger remove" type="button"><i
                                        class="bi bi-dash"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>

            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->


<!-- REQUIRED SCRIPTS -->

{% endblock content %}


{% block js_script %}
<script src="{% static 'dist/js/pages/dashboard3.js' %}"></script>
{% endblock js_script %}

templates/questions/edit.html
{% extends "core/admin_base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block page_title %}
<title>Quiz Questions</title>
{% endblock page_title %}

{% block head %}
{% endblock head %}

{% block content %}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">{% if form.instance.id %}Edit {% else %}Create {% endif %}Question For "{{quiz.title}}"</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">Quiz Questions</li>
                        <li class="breadcrumb-item"><a href="{% url 'quiz_questions' quiz.id %}">Quiz Questions List</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">{% if form.instance.id %}Edit {% else %}Create {% endif %}</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
                <form method="POST">
                <div class="card-body">
                  {% csrf_token %}
                    {% bootstrap_form form %}
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>

            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->


<!-- REQUIRED SCRIPTS -->

{% endblock content %}


{% block js_script %}
<script src="{% static 'dist/js/pages/dashboard3.js' %}"></script>
{% endblock js_script %}

templates/questions/index.html
{% extends "core/admin_base.html" %}

{% load static %}

{% block page_title %}
<title>Profile</title>
{% endblock page_title %}

{% block head %}
{% endblock head %}

{% block content %}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Questions for "{{quiz.title}}"</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">Quiz Questions</li>
                        <li class="breadcrumb-item"><a href="{% url 'add_quiz_questions' quiz.id %}">Add Question to Quiz</a></li>

                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header border-0">
                            <h3 class="card-title">List</h3>
<!--                            <div class="card-tools">-->
<!--                                <a href="#" class="btn btn-tool btn-sm">-->
<!--                                    <i class="fas fa-download"></i>-->
<!--                                </a>-->
<!--                                <a href="#" class="btn btn-tool btn-sm">-->
<!--                                    <i class="fas fa-bars"></i>-->
<!--                                </a>-->
<!--                            </div>-->
                        </div>
                        <div class="card-body table-responsive p-0">
                            <table class="table table-striped table-valign-middle">
                                <thead>
                                <tr>
                                    <th>Text</th>
                                    <th>Answers</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for question in questions %}
                                <tr>
                                    <td>  <h5>{{question.text}}</h5></td>
                                    <td>
                                        {% for answer in question.answer_set.all %}
                                            <h5>{{answer.text}}
                                                <a href="{% url 'edit_answer' answer.id %}">( Edit Answer )</a>

    <!--                                            <a href="{% url 'delete_answer' answer.id %}">Delete</a>-->
                                                <br>
                                            </h5>
                                        {% endfor %}

                                    </td>
                                    <td>
<!--                                        <a type="button" href="{% url 'answers_of_question' question.id %}" class="btn btn-primary">Answers List</a>-->

<!--                                        <a type="button" href="{% url 'add_answers_to_question' question.id %}" class="btn btn-primary">Add Answer to Question</a>-->

                                        <a type="button" href="{% url 'edit_question' question.id %}" class="btn btn-secondary">Edit</a>

                                        <a type="button" href="{% url 'delete_quiz_question' question.id %}" class="btn btn-danger">Delete</a>

                                    </td>
                                </tr>

                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col-md-6 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->


<!-- REQUIRED SCRIPTS -->

{% endblock content %}


{% block js_script %}
<script src="{% static 'dist/js/pages/dashboard3.js' %}"></script>
{% endblock js_script %}